sequenceDiagram
    participant gkk as greenkeeper-keeper
    participant gk as greenkeeper
    participant gh as GitHub
    participant cs as check service(s)

    activate gh
    gk->>gh: dependency update PR
    gh->>+cs: trigger status-check
    cs->>-gh: status-check result
    activate gkk
    activate gkk
    gh->>+gkk: Successful webhook from greenkeeper
    gkk->>+gh: request PRs related to PR commit
    gh-->>-gkk: list of PRs for PR commit
    alt no PRs for commit
        gkk->>gh: bad request
    end
    alt more than one PR for commit
        gkk->>gh: bad request
    end
    alt PR is not from greenkeeper
        gkk->>gh: bad request
    end
    gkk->>gh: event will be processed
    deactivate gkk
    gkk->>+gh: get combined status for ref
    gh-->>-gkk: combined status
    gkk->>+gh: list checks for ref
    gh-->>-gkk: checks list
    gkk->>gh: accept PR
    deactivate gkk
    deactivate gh
